title: Linguistic Fingerprints of Reddit Communities
description: 
show_downloads: false
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md